{% set name = "nllgrid" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nllgrid-{{ version }}.tar.gz
  sha256: f67d2a8492e160576ea4a81e2c76ad09e57ed47aaadfd8a4a8cd2b2f16db6d5e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.0
    - pyproj
    - python >=3.6
    - scipy >=0.16

test:
  imports:
    - nllgrid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/claudiodsf/nllgrid
  summary: Python class for reading and writing NonLinLoc grid files
  license: CECILL-2.1
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - claudiodsf
