{% set name = "nllgrid" %}
{% set version = "1.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nllgrid-{{ version }}.tar.gz
  sha256: 7bf244a1cae72c75dfd17f57ad50411046c1faff0abbb01c929662b62b4a112f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - versioneer
    - python >=3.7
  run:
    - numpy >=1.0
    - scipy >=0.16
    - pyproj
    - python >=3.7

test:
  imports:
    - nllgrid
  source_files:
    - tests
    - tests/data
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home: https://github.com/claudiodsf/nllgrid
  summary: Python class for reading and writing NonLinLoc grid files
  license: CECILL-2.1
  license_file: LICENSE.txt
  description: |
    Python class for reading and writing NonLinLoc grid files.
  dev_url: https://github.com/claudiodsf/nllgrid

extra:
  recipe-maintainers:
    - claudiodsf
